inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance

AllCops:
  Exclude:
    - "bin/*"
    - "db/*"
    - "vendor/**/*"
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
