name: Ruby

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.152.0
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Rubocop
        run: rubocop
      - name: Run tests
        run: bundle exec rake
